### ISSUE TITLE
Adding order edit to the jvm SDK

### ISSUE THREAD

**Issue by acbeni** [commercetools/commercetools-jvm-sdk#1876]
This is an umbrella issue to add order edit feature to the JVM sdk.

* [x] [create the read write, get by id, key ... endpoints](https://github.com/commercetools/commercetools-jvm-sdk/issues/1877)
* [x] [add staged actions.](https://github.com/commercetools/commercetools-jvm-sdk/issues/1878)
* [x] [add support for the apply order edit endpoint](https://github.com/commercetools/commercetools-jvm-sdk/issues/1879)
* [x] [document the new SDK feature](https://github.com/commercetools/commercetools-jvm-sdk/issues/1886)

**Comment by skyriakou** [comment]
closes #1827
