### ISSUE TITLE
Automatic code generation for categories & products endpoint in JVM SDK

### ISSUE THREAD

**Issue by skyriakou** [commercetools/commercetools-jvm-sdk#1944]
### What?
Automatic code generation for categories & products endpoint in JVM SDK

### Why?
Proof of concept if the new code generation approach works

### Acceptance criteria
- [ ] Generate model classes
- [ ] Generate model draft builders
- [ ] Generate requests
- [ ] Generate request builders
- [ ] Api root with request builders
- [ ] Adjust RAML files

**Comment by skyriakou** [comment]
Estimation: 1 month

**Comment by alex-ct** [comment]
Implemented.
