### ISSUE TITLE
Test compatibility of JDKs with our JVM SDK and document - Related to: https://jira.commercetools.com/browse/SUPPORT-5828

### ISSUE THREAD

**Issue by skyriakou** [commercetools/commercetools-jvm-sdk#1967]
### What?
Test compatibility of JDKs with our JVM SDK and document - Related to: https://jira.commercetools.com/browse/SUPPORT-5828

###Why?

To provide users of the SDK an overview of the compatible JDKs

### Acceptance criteria

- [x] All tests pass on OpenJDK & Oracle 
- [x] All tests pass amazon corretto (optional)
- [x] This information can be reached publicly
